### ISSUE TITLE
Panic in member list

### ISSUE THREAD

**Issue by Edremon** [terminal-discord/weechat-discord#101]
I have been using weechat-discord (mk3 branch) in the last few days and after some time, around 1-2 hours, it panic, here what's in printed in weechat:
```
Panic in the main Weechat thread: panicked at 'removal index (is 99) should be < len (is 99)', src/twilight_utils/member_list.rs:100:31
discord: event loop failed, stopping...
discord: event loop failed, stopping...
discord: event loop failed, stopping...
```

Here what I have in tracing in a normal session right after logging in, I don't know if all those errors are relevant:
```
ERROR twilight_gateway::shard::json: invalid JSON: {"t":"THREAD_LIST_SYNC","s":43,"op":0,"d":{"threads":[{"type":11,"thread_metadata":{"locked":false,"invitable":true,"create_timestamp":null,"auto_archive_duration":10080,"archived":false,"archive_timestamp":"redacted"},"rate_limit_per_user":0,"parent_id":"redacted","owner_id":"redacted","name":"redacted","message_count":50,"member_ids_preview":["redacted","redacted","redacted","redacted"],"member_count":4,"last_pin_timestamp":"redacted","last_message_id":"redacted","id":"redacted","guild_id":"redacted","flags":0}],"most_recent_messages":[{"type":0,"tts":false,"timestamp":"redacted","referenced_message":null,"pinned":false,"nonce":"redacted","mentions":[],"mention_roles":[],"mention_everyone":false,"is_thread_dispatch":true,"id":"redacted","flags":0,"embeds":[],"edited_timestamp":null,"content":"redacted","components":[],"channel_id":"redacted","author":{"username":"redacted","public_flags":512,"id":"redacted","discriminator":"0500","avatar_decoration":null,"avatar":"redacted"},"attachments":[]}],"guild_id":"redacted"}}
ERROR twilight_gateway::shard::processor::r#impl: processing incoming event failed: ProcessError { kind: ParsingPayload, source: Some(GatewayEventParsingError { source: Some(Error("missing field `members`", line: 1, column: 1260)), kind: Deserializing }) } shard_id=0 shard_total=1
ERROR weecord::hooks::signals: Error acking channel history: failed to deserialize response body guild_id=Some(Id<GuildMarker>(redacted)) channel_id=Id<ChannelMarker>(redacted)
```
The first error seem to be about an active thread (that I haven't joined). The third one seem to be about a channel where I have unread messages.

I will update issue if I get more relevant logs when that error happen again.

**Comment by Edremon** [comment]
The panic didn't happen today, when it happened multiple times yesterday, don't have any idea what is different, connected to the same exact channels.

Concerning the errors that I posted in my initial bug report, they don't seem to be related, I got the ack one a lot but that just seem seem to make reading state a bit weird.

Meanwhile, I also got new errors that seem to be more related: [paste since it's quite big](https://gist.github.com/Edremon/220bea6aa6fabdd661189eb5303b7092). It's always the same with the same two users in it being spammed quite frequently (currently 300k lines in buffer).

**Comment by Edremon** [comment]
Happened again, I don't see anything special in traces.

In weechat core:
```
hh:26:38	=!=	Panic in the main Weechat thread: panicked at 'removal index (is 99) should be < len (is 99)', src/twilight_utils/member_list.rs:99:31
hh:26:38		discord: event loop failed, stopping...
hh:26:41		discord: event loop failed, stopping...
hh:26:44		discord: event loop failed, stopping...
hh:26:44		discord: event loop failed, stopping...
hh:26:44		discord: event loop failed, stopping...
hh:26:44		discord: event loop failed, stopping...
hh:26:45		discord: event loop failed, stopping...
hh:26:45		discord: event loop failed, stopping...
hh:26:46		discord: event loop failed, stopping...
hh:26:46		discord: event loop failed, stopping...
hh:26:46		discord: event loop failed, stopping...
hh:26:46		discord: event loop failed, stopping...
```
In weecord log:
```
hh:26:38		ERROR weecord::discord::discord_connection: Event loop failed: channel closed
hh:26:41		ERROR weecord::discord::discord_connection: Event loop failed: channel closed
hh:26:34		ERROR weecord::discord::discord_connection: Event loop failed: channel closed
hh:26:34		ERROR weecord::discord::discord_connection: Event loop failed: channel closed
hh:26:34		ERROR weecord::discord::discord_connection: Event loop failed: channel closed
hh:26:34		ERROR weecord::discord::discord_connection: Event loop failed: channel closed
hh:26:35		ERROR weecord::discord::discord_connection: Event loop failed: channel closed
hh:26:35		ERROR weecord::discord::discord_connection: Event loop failed: channel closed
hh:26:36		ERROR weecord::discord::discord_connection: Event loop failed: channel closed
hh:26:36		ERROR weecord::discord::discord_connection: Event loop failed: channel closed
hh:26:36		ERROR weecord::discord::discord_connection: Event loop failed: channel closed
hh:26:k6		ERROR weecord::discord::discord_connection: Event loop failed: channel closed
```
In the 30 minutes before panic, it only had a few errors related to ack.

**Comment by Edremon** [comment]
It happened again without any of the `Nick list in an invalid state` error, so that might also be unrelated.

**Comment by Edremon** [comment]
> Can you double check if there are any Failed to add group "{}" to nicklist errors? That could lead to this panic happening.

No `Failed to add group "{}" to nicklist` errors at all.

> Do you have a very reliable internet connection, or is it possible that the client disconnected briefly?

AFAIK my network connection is reliable.

> Are you in any very large group chats (100 users or more?)

Some have more than 10k members.

> Were you actively using weecord? Specifically adding or removing channels or servers? Or was it left completely idle with no channels or guilds added or removed since weechat was opened?

Hmm most of the time, I'm on some irc channel when that happen. In those session, I have never added or removed channels/guild, only use autoconnect.
